export const GAME_CONFIG = {
	GOAL: 1000,
	ANIMATION: {
		SPILL_DURATION: 3000,
		WAVE_DURATION: 20,
		GOD_RAYS_DURATION: 3000,
		SPARKLE_DURATION: 3000,
	},
	PARTICLES: {
		FLOATING_COUNT: 30,
		SPLASH_COUNT: 24,
		SPARKLE_COUNT: 20,
	},
	REFRESH_INTERVALS: {
		LEADERBOARD: 10000,
	},
};
