/**
 * Kick Chat Integration Constants
 */

// Pusher WebSocket configuration
export const KICK_PUSHER_CONFIG = {
	APP_KEY: "32cbd69e4b950bf97679",
	WS_URL: "wss://ws-us2.pusher.com/app",
	PROTOCOL_VERSION: 7,
	CLIENT: "js",
	VERSION: "8.4.0-rc2",
} as const;

// Chat trigger words (compared in lowercase)
export const CHAT_TRIGGERS = {
	GREETING: [
		// Standart selamlar
		"merhaba",
		"merhabalar",
		"mrb",
		"mrblar",
		"selam",
		"selamm",
		"selammm",
		"selammmm",
		"selamlar",
		"selamlarr",
		"slm",
		"slmm",
		"slmlar",
		// Selamın aleyküm varyasyonları
		"selamün aleyküm",
		"selamun aleykum",
		"selamunaleyküm",
		"selamunaleykum",
		"as",
		"sa",
		"sea",
		"seaa",
		"as sa",
		"aleyküm selam",
		"aleykum selam",
		// İngilizce selamlar
		"hey",
		"heyy",
		"heyyy",
		"heyyyy",
		"hi",
		"hii",
		"hiii",
		"hiiii",
		"hello",
		"helloo",
		"hellooo",
		"helo",
		"heloo",
		"helooo",
		"yo",
		"yoo",
		"sup",
		"whats up",
		"wassup",
		// Günün saatine göre
		"günaydın",
		"gunaydin",
		"günaydınlar",
		"gunaydinlar",
		"tünaydın",
		"tunaydin",
		"iyi günler",
		"iyi gunler",
		"iyi akşamlar",
		"iyi aksamlar",
		// Yayın spesifik
		"iyi yayınlar",
		"iyi yayinlar",
		"hayırlı yayınlar",
		"hayirli yayinlar",
		"bereketli yayınlar",
		"bol şans",
		"bol sans",
		// Giriş bildirimi
		"geldim",
		"ben geldim",
		"buradayım",
		"buradayim",
		"geldik",
		"burdayım",
		"burdayim",
		"yetişebildim",
		"yetistim",
		"yakaladım",
		"yakaladim",
		// Hoş geldin/bulduk
		"hoşbulduk",
		"hosbulduk",
		"hoş bulduk",
		"hos bulduk",
		// Chat ve topluluk
		"selam chat",
		"selam millet",
		"selam dostlar",
		"selam arkadaşlar",
		"selam arkadaslar",
		"selam gençler",
		"selam gencler",
		"selam tayfa",
		"selam herkese",
		"herkese selam",
		"herkese merhaba",
		"selam portakal",
		"selam portakallar",
		// Kısaltmalar ve slang
		// Note: "nbr" is in QUESTION category (short for "ne haber")
		"slm nbr",
		"meraba",
		"merabalar",
		"merba",
		"salam",
		"salamlar",
	],
	FAREWELL: [
		// Standart vedalar
		"görüşürüz",
		"gorusuruz",
		"görüşürük",
		"gorusuruk",
		"görüşmek üzere",
		"gorusmek uzere",
		"hoşçakal",
		"hoscakal",
		"hoşça kal",
		"hosca kal",
		"hoşçakalın",
		"hoscakalin",
		// Bay bay varyasyonları
		"babay",
		"babays",
		"bays",
		"bay bay",
		"baybay",
		"bayy",
		"bb",
		"bbb",
		"bbbb",
		// İngilizce vedalar
		"bye",
		"byee",
		"byeee",
		"bye bye",
		"byebye",
		"by",
		"byy",
		"byyy",
		"cya",
		"see ya",
		"see you",
		"later",
		"peace",
		"peace out",
		// Güle güle
		"güle güle",
		"gule gule",
		"gülegüle",
		"gulegule",
		// Gece spesifik
		"iyi geceler",
		"geceniz güzel geçsin",
		"tatlı rüyalar",
		"tatli ruyalar",
		// Dini vedalar
		"allah'a emanet",
		"allaha emanet",
		"allah'a ısmarladık",
		"allaha ismarladik",
		"hayırlı geceler",
		"hayirli geceler",
		// Gidiş bildirimi
		"gidiyorum",
		"ben gidiyorum",
		"ben kaçar",
		"ben kacar",
		"ben kaçtım",
		"ben kactim",
		"kaçar ben",
		"kacar ben",
		"kaçıyorum",
		"kaciyorum",
		"çıkıyorum",
		"cikiyorum",
		"ben çıkayım",
		"ben cikayim",
		// Resmi vedalar
		"müsaadenizle",
		"musadenizle",
		"izninizle",
		"hadi eyvallah",
		"eyvallah",
		"eyv",
		// Yayın sonu
		"iyi yayınlar dilerim",
		"iyi yayınlardı",
		"güzel yayındı",
		"guzel yayindi",
		"yayının devamını izleyemiyorum",
		// Kaçış bahaneleri/sebepleri
		"yatmaya gidiyorum",
		"ben yatar",
		"uykum geldi",
		"sabah is var",
		"sabah iş var",
		"okul var",
		"yarın erken kalkıcam",
		"yarin erken kalkicam",
		"gözlerim kapandı",
	],
	CHEER: [
		// Tebrik ve övgü
		"aferin",
		"aferim",
		"helal",
		"helall",
		"helalll",
		"helal olsun",
		"helal sana",
		"helal be",
		"bravo",
		"bravoo",
		"bravooo",
		"tebrikler",
		"tebrik ederim",
		// Kalite övgüsü
		"süper",
		"super",
		"süperr",
		"süperrr",
		"harika",
		"harikaa",
		"harikaaa",
		"muhteşem",
		"muhtesem",
		"efsane",
		"efsanee",
		"efsaneee",
		"mükemmel",
		"mukemmel",
		"kusursuz",
		"şahane",
		"sahane",
		"enfes",
		"olağanüstü",
		"olaganüstü",
		// Güzel/iyi
		"güzel",
		"guzel",
		"güzell",
		"guzell",
		"çok güzel",
		"cok guzel",
		"çok iyi",
		"cok iyi",
		"bayağı iyi",
		"bayagi iyi",
		"fena değil",
		"fena degil",
		"iyi iyi",
		// Gaming terimleri
		"nice",
		"nicee",
		"niceee",
		"pog",
		"poggers",
		"pogchamp",
		"pogg",
		"gg",
		"ggwp",
		"gg wp",
		"wp",
		"wpp",
		"gj",
		"good job",
		"nt",
		"nice try",
		"ez",
		"ezpz",
		"clutch",
		"insane",
		"sick",
		"godlike",
		"goated",
		"cracked",
		// Türkçe gaming slangi
		"yargı",
		"yargi",
		"yargıladın",
		"yargiadin",
		"şov",
		"sov",
		"şovv",
		"sovv",
		"aktı",
		"akti",
		"akıttın",
		"akittin",
		"temiz",
		"temizz",
		"temizzz",
		"clean",
		"maşallah",
		"masallah",
		"vay be",
		"vay bee",
		"vayy",
		"vayyy",
		// Kral/büyük övgüsü
		"kral",
		"krall",
		"kralll",
		"kralsın",
		"kralsin",
		"büyüksün",
		"buyuksun",
		"adam",
		"adamm",
		"adamsın",
		"adamsin",
		"patron",
		"reis",
		"boss",
		"goat",
		// Gen Z / Twitch Slang
		"w",
		"big w",
		"massive",
		"huge",
		"bet",
		"sheesh",
		"sheeesh",
		"yapıyorsun bu sporu",
		"yapiyorsun bu sporu",
		"bu işi biliyorsun",
		"bu isi biliyorsun",
		"dayı naptın",
		"dayi naptin",
		"oynamayı biliyorsun",
		// Eline sağlık
		"eline sağlık",
		"eline saglik",
		"ellerine sağlık",
		"ellerine saglik",
		// Dilek ve teşvik
		"başarılar",
		"basarilar",
		"başarılarını",
		"kolay gelsin",
		"devamını",
		"devamini",
		"devam",
		"devamm",
		"devamke",
		// Heyecan ifadeleri
		"leeet's goooo",
		"lets go",
		"let's go",
		"hadi",
		"hadii",
		"hadiii",
		"hadi be",
		"ohaa",
		"ohaaa",
		"ohaaaa",
		// Note: vay/vayy/vayyy are already in the earlier section
		"of ya",
		"off",
		"offf",
		"wow",
		"woww",
		"wowww",
	],
	QUESTION: [
		// Nasılsın varyasyonları
		"nasılsın",
		"nasilsin",
		"nasılsınız",
		"nasilsiniz",
		"nasıl",
		"nasil",
		"nası",
		"nasi",
		"nasısın",
		"nasisin",
		"n'asılsın",
		"nasilsn",
		// Ne haber varyasyonları
		"naber",
		"naberr",
		"naberrr",
		"n'aber",
		"nb",
		"nbr",
		"ne haber",
		"ne haberler",
		"ne var ne yok",
		"neler var",
		"neler oluyor",
		// Nasıl gidiyor
		"nasıl gidiyor",
		"nasil gidiyor",
		"nasıl gidiyo",
		"nasil gidiyo",
		"nası gidiyo",
		"nasi gidiyo",
		"işler nasıl",
		"isler nasil",
		// Keyif/durum sorgusu
		"keyifler nasıl",
		"keyifler nasil",
		"durumlar nasıl",
		"durumlar nasil",
		"moraller nasıl",
		"moraller nasil",
		"enerji nasıl",
		"enerji nasil",
		// İyi misin
		"iyi misin",
		"iyi misiniz",
		"iyimisin",
		"iyisin",
		"her şey yolunda mı",
		"hersey yolunda mi",
		// Slang sorular
		"ne diyon",
		"nediyon",
		"napıyon",
		"napiyon",
		"napıyosun",
		"napiyosun",
		"ne yapıyorsun",
		"ne yapiyorsun",
	],
} as const;

// Response templates ({username} is replaced with actual username)
export const CHAT_RESPONSES = {
	GREETING: [
		"Merhaba {username}! 🍊",
		"Selam {username}! ✨",
		"Hoş geldin {username}! 🎉",
		"Hey {username}! 👋",
		"Naber {username}! 🍊✨",
		"Aa {username} gelmiş! Hoş geldin! 🍊",
	],
	FAREWELL: [
		"Görüşürüz {username}! 👋",
		"Bay bay {username}! 🍊",
		"Hoşça kal {username}! ✨",
		"Kendine iyi bak {username}! 🍊👋",
		"Sonra görüşürüz {username}! 👋",
		"Yine bekleriz {username}! 🍊",
	],
	CHEER: [
		"Teşekkürler {username}! 🍊✨",
		"Çok sağ ol {username}! ✨",
		"Teşekkürler desteğin için! {username} 🍊",
		"Portakal power! 🍊⚡",
	],
	QUESTION: [
		"İyiyim {username}, teşekkürler! Sen nasılsın? 🍊",
		"Süper gidiyor {username}! ✨",
		"Çok iyiyim {username}! 🍊✨",
		"Her şey yolunda {username}! 👍",
		"Harikayım {username}! Sen? 🍊",
	],
} as const;

// Chat configuration
export const CHAT_CONFIG = {
	REACTION_DURATION: 4000, // Reaction display duration (ms)
	USER_COOLDOWN: 30000, // Min interval for same user (ms)
	REACTION_COOLDOWN: 2000, // Min interval between reactions (ms)
	RECONNECT_DELAY: 5000, // WebSocket reconnect delay (ms)
	MAX_RECONNECT_ATTEMPTS: 5, // Max reconnect attempts
} as const;

// Fuzzy matching configuration for typo tolerance
export const FUZZY_MATCH_CONFIG = {
	ENABLED: true, // Enable/disable fuzzy matching
	// Short words (≤3 chars): max Levenshtein distance
	SHORT_WORD_MAX_DISTANCE: 0, // Exact match only
	SHORT_WORD_LENGTH: 3,
	// Medium words (4-7 chars): min similarity ratio (stricter to avoid false positives)
	MEDIUM_WORD_MIN_SIMILARITY: 0.82,
	MEDIUM_WORD_MAX_LENGTH: 7,
	// Long words (≥8 chars): min similarity ratio
	LONG_WORD_MIN_SIMILARITY: 0.8,
	// Preprocessing options
	NORMALIZE_TURKISH: true, // Convert ş→s, ğ→g, etc.
	REMOVE_REPEATED_CHARS: true, // "selammmm" → "selam"
} as const;

// Face indices by reaction type
// 0: Default, 1: Happy, 2: Surprised, 3: Wink, 4: Excited, 5: Dead, 6: Dizzy, 7: Cool, 8: King, 10: Rich, 11: Ninja
export const REACTION_FACES = {
	GREETING: [1, 3, 4], // HappyFace, WinkFace, ExcitedFace
	FAREWELL: [3, 7], // WinkFace, CoolFace
	CHEER: [4], // ExcitedFace
	QUESTION: [1, 2, 3], // HappyFace, SurprisedFace, WinkFace
} as const;
